# Generated by Django 5.1.1 on 2024-11-15 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounterParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('product_type', models.CharField(choices=[('Option', 'Option'), ('Forward', 'Forward'), ('Future', 'Future'), ('Swap', 'Swap'), ('SwapCrossCurrency', 'SwapCrossCurrency'), ('Spot', 'Spot'), ('Standard', 'Standard')], default='Standard', max_length=20)),
                ('product_class', models.CharField(choices=[('Bond', 'Bond'), ('Equity', 'Equity'), ('Interst', 'Interest'), ('Forex', 'Forex'), ('Commodities', 'Commodities')], default='Bond', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TradingBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='book', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.counterparty')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('tradingbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tradingbook')),
            ],
        ),
    ]
